#!/usr/bin/env bash

function main {
  local shome="${_facts_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  
  local tmp_facts="$(mktemp -t XXXXXX)"
  env NO_FACTS_CACHE=1 facts . > "$tmp_facts"
  ln -nfs "$tmp_facts" "$shome/.facts.json"
}

source sub "$BASH_SOURCE" "$@"
